services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MASTER_DATABASE_URL=sqlite:///./master.db

networks:
  app-network:
    driver: bridge
